//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankWPFApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodStock
    {
        public int bloodStockId { get; set; }
        public string bloodBank { get; set; }
        public string bloodGroup { get; set; }
        public int numberOfBottles { get; set; }
        public string city { get; set; }
        public string phoneNo { get; set; }
    }
}
